### ISSUE TITLE
Empty default branch

### ISSUE THREAD

**Issue by JamesBremner** [DM-UK/MapMate#2]
You have two development branches.  The default branch is empty of code.

**Comment by DM-UK** [comment]
Thank you, Github is new to me, I shall look at merging branches.

**Comment by JamesBremner** [comment]
No need to merge.  ( merge is a challenge the first time you try it.

- Decide which branch you want to keep
- Make chosen branch default
- Delete other branch

This issue should be assigned to you.

**Comment by DM-UK** [comment]
Thank you. I thought the GitHub interface would be more intuitive but i'm having problems!

**Comment by JamesBremner** [comment]
Is this the first time you have used version control?  It is an extremely important skill, without which it is impossible to develop reliable, quality code.  First lesson: relax - it is almost to mess things up beyond recovery.

**Comment by DM-UK** [comment]
> Is this the first time you have used version control?

Yes! I'm a self taught hobbyist programmer and while I understand the basics of computing, I've not picked up this skill, since I've never published any of my own code!

The stackoverflow question was the first I have ever asked. I'd really appreciate if you would have a quick glance at my (Java) code and point out any bad code.

**Comment by JamesBremner** [comment]
Let's get you up to speed on version control first.  There is no point in writing code, good OR bad, if you do not know how to keep it safe under version control.

**Comment by DM-UK** [comment]
Default branched changed to master

**Comment by JamesBremner** [comment]
You still have two branches.  

![image](https://github.com/user-attachments/assets/b8196c2c-56e4-45b6-a231-6a6c3cb2aa9f)

Do not close an issue until the work is complete and the person who opened the issue has signed off on it.

**Comment by DM-UK** [comment]
Deleted thank you.
